--@field interpolation function
Config = {
    { time = 0,
        value = 0,
        interpolation = "none"
    },
    { time = 500,
        value = 1,
        interpolation = "none",
    },
    { time = 1000,
        value = 2,
        interpolation = "none",
    },
    { time = 1500,
        value = 3,
        interpolation = "none",
    },
    { time = 2000,
        value = 4,
        interpolation = "none",
    },
    { time = 2500,
        value = 5,
        interpolation = "none",
    },
    { time = 3000,
        value = 6,
        interpolation = "none",
    },
    { time = 3500,
        value = 7,
        interpolation = "none",
    },
}
